client_version: "1.0.0"
runtime_dir: ""
server_url: "http://154.64.255.139:43090"
machine_id: ""
agent_token: ""
bit_api: ""
api_token: ""
bitbrowser_cdp_connect_retry_count: 120
bitbrowser_cdp_connect_retry_delay: 0.6
bitbrowser_cdp_refresh_every: 6
task_settings:
  speed_factor: 0.85
  stranger_limit_cache_ms: 1200
  send_interval_seconds:
  - 0
  - 0
